# Generated by Django 6.0.1 on 2026-06-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xeon', '0002_alter_income_options_alter_todo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('bank', 'Bank Transfer')], default='cash', max_length=10),
        ),
    ]
